[package]
name = "generative"
version = "0.1.0"
authors = ["Gaurav Patel <GauravPatel97@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon-rs = "0.3.0"
perlin2d = "0.2.6"